### ISSUE TITLE
What's your process for organizing/labeling issues?

### ISSUE THREAD

**Issue by hossameldeen** [staltz/ama#44] opened 2018-12-19 11:56 UTC
E.g, in [manyverse](https://gitlab.com/staltz/manyverse/boards), you seem to have a key-value system for labels, with keys being `priority`, `scope`, and `type`. But you also seem to have other labels like `~testing`.

Is it indeed a key-value system? If so, what all are the keys & their values' meaning? (e.g., `type: dx`). Or, in general, what's your current process/best practice for labeling and organizing issues?

Thanks in advance! :)

**Comment by staltz** [comment] 2018-12-21 10:40
Glad that you asked! I feel quite productive with the process I have right now, although it's at the moment only for myself, not a team. That said, I took inspiration from the [Cycle.js label process](https://github.com/cyclejs/cyclejs/labels), and that's a project with a team of maintainers, where the process has been working well for a team of 3. Here's how the process works in Manyverse:

For every issue, pick a **type**, a **scope**, and a **priority**:

- **Type** indicates whether the issue is relevant to users (ux) or only to developers (dx)
  - `dx` means "developer experience" so these are issues that are related to refactoring, improving build system, tests, etc
  - `ux` means "user experience" and can be either `ux feature` or `ux bug fix` to indicate to the user what kind of improvement this was
  - Every git commit message starts with either `ux: ...` or `dx: ...`, and the changelog is generated from the commit history, where only `ux` commit messages are shown. This means the commit messages are literally the changelog that appears to users when they update the app
- **Scope** indicates in what part of the codebase this issue affects. So far the codebase has only two relevant "places":
  - `scope: backend` refers to the background Node.js project running the SSB server
  - `scope: frontend` refers to the UI code in React Native and Cycle.js
  - In the future there should be `scope: android` and `scope: ios` and maybe `scope: desktop`
- **Priority** indicates how urgent/important the issue is, and I use 4 weights:
  - `priority 1 (maybe)` this is something we will maybe do
  - `priority 2 (could)` this is something we could do
  - `priority 3 (should)` this is something we should do
  - `priority 4 (must)` this is something we must do

There's also a rule for `priority` labeling: `must < should < could < maybe`. In other words, the number of `must` issues has to be less than the number of `should` issues, which has to be less than the number of `could` issues, etc. This gives a funnel shape to the kanban board, see below:

![screenshot from 2018-12-21 12-20-23](https://user-images.githubusercontent.com/90512/50337870-1371ed00-051b-11e9-8451-ef5d02a8e470.png)

Because there's basically only me working so far on Manyverse, there should be only 1 issue "work in progress". Ideally, in a team of N developers, there are N issues work in progress. In the "must" column, there are usually 2~4 issues, which means at any time I choose the next work to do, I only have to pick one from three. I try to keep a somewhat golden ratio progression (i.e. more than 1x, less than 2x multiplication) to the shape of the funnel, but it doesn't need to be so strictly organized. The importance of organizing the issues is also proportional to the priority:

- It's *very* important to keep the "must" column organized and well chosen
- It's *somewhat* important to keep the "should" column organized and well chosen
- It's not that important to keep the "could" column organized
- It's not important to keep the "maybe" column organized

Once in a while, as issues get done, I go through the issues in lower priorities and begin promoting them to higher levels. You can think of this funnel as a job interview process with multiple stages of interviews. I try to imagine which of these issues "earns its spot" the best. And I usually give priority to commonly experienced bugs, because I think it's only worth building new features after the current user experience is mostly bugless.

This funnel shape also works for the [Feature roadmap](https://gitlab.com/staltz/manyverse/wikis/roadmap), which is kind of like a backlog, but less actionable, it's basically a backlog of ideas, while the issues are a backlog of tasks to perform as a developer.

Then there are less important issues, that are used just for communication:

- `~ work in progress` used just to create a column in the kanban board
- `~ testing` also for having a column in the kanban board, indicates issues that were developed but need further testing before releasing
- `type: discussion` discussion issues are not issues (tasks) at all, but sometimes people open these, so I don't want to delete them
- `closed because: ...` which inform why a certain issue was closed, e.g.
  - `closed because: fixed` ("done")
  - `closed because: is discussion` this one is used for every `type: discussion` issue because I don't want discussions to seem like actionable tasks, but I don't want closing to feel like dismissal of the conversation, this turns out to be quite useful as people understand that all discussion issues are closed by default
  - etc
- `~ contribute` just an indicator that the maintainers would gladly welcome anyone to try out solving this issue

While this process is yet to be proven on a larger scale (more issues and more developers), so far I really like the funnel shaped backlog.

**Closed as completed by staltz** 2018-12-21 10:40 UTC
